# -*- coding: utf-8 -*-
"""armenianBankAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-w5y7s_huK1rDZhihlk17UDd_UrBIUMP
"""

!pip install openai

import os, getpass

os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter API key: ")

from openai import OpenAI
import json

client = OpenAI()

with open("bankData (2).json", "r", encoding="utf-8") as f:
    data = json.load(f)

print("Loaded:", len(data))

context = json.dumps(data, ensure_ascii=False)

allowed_keywords = [
    "վարկ", "վարկեր",
    "ավանդ", "ավանդներ",
    "մասնաճյուղ", "մասնաճյուղեր"
]

def is_allowed_question(user_input):
    user_input = user_input.lower()
    return any(word in user_input for word in allowed_keywords)

def ask_ai(user_input):
    if not is_allowed_question(user_input):
        return "Կներեք, կարող եմ պատասխանել միայն վարկերի, ավանդների և մասնաճյուղերի մասին հարցերին։"

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": f"""
Դու բանկային AI օգնական ես։

ԿԱՆՈՆՆԵՐ:
1. Պատասխանիր միայն վարկերի, ավանդների և մասնաճյուղերի մասին։
2. Օգտագործիր միայն տրված տվյալները:
3. Առաջին հերթին, վերլուծիր օգտատիրոջ հարցը՝ բացահայելու համար հարցի թեման (օրինակ՝ 'credits', 'deposits', 'branches'):
4. Հետո, որոնիր համապատասխան թեմա տրված 'context' JSON զանգվածում։
5. Երբ գտնես համապատասխան թեմա, գտիր այդ թեմային վերաբերող գրառումը 'context'-ում և ստուգիր, թե արդյոք այն պարունակում է 'response_template' դաշտ։
6. Եթե 'response_template' դաշտը առկա է, ապա այն օգտագործիր որպես պատասխանի հիմք։
7. Լրացրու 'response_template'-ի մեջ առկա բոլոր փոխարինողները (օրինակ՝ {{types}}, {{interest_rate_range}}) համապատասխան արժեքներով, որոնք պետք է գտնես նույն գրառման 'data' դաշտից։
8. ՄԻԱՅՆ այն դեպքում, եթե չես կարողանում գտնել համապատասխան թեմա, կամ եթե թեմայի տվյալները չկան, կամ եթե 'response_template'-ը հնարավոր չէ լրացնել անհրաժեշտ տվյալների բացակայության պատճառով, պատասխանիր 'Չեմ կարող պատասխանել'։
9. Մի հորինիր ոչինչ։
10. Պատասխանները լինեն կարճ և հստակ։

ՏՎՅԱԼՆԵՐ:
{context}
"""
            },
            {
                "role": "user",
                "content": user_input
            }
        ]
    )

    return response.choices[0].message.content

print(ask_ai("Ինչ վարկեր ունեք"))
print(ask_ai("Ավանդների մասին ասա"))
print(ask_ai("Որտե՞ղ է մասնաճյուղը"))
print(ask_ai("Ո՞վ է Հայաստանի նախագահը"))

while True:
    user_input = input("Դու: ")

    if user_input.lower() in ["exit", "quit"]:
        break

    response = ask_ai(user_input)
    print("AI:", response)

!pip install gtts

from gtts import gTTS
from IPython.display import Audio

def speak(text):
    tts = gTTS(text=text, lang='en')
    tts.save("response.mp3")
    return Audio("response.mp3", autoplay=True)

speak("Բարև, սա փորձ է")

!pip install soundfile

import soundfile as sf
from IPython.display import Audio

def speak_openai(text):
    audio = client.audio.speech.create(
        model="gpt-4o-mini-tts",
        voice="alloy",
        input=text
    )

    with open("response.wav", "wb") as f:
        f.write(audio.content)

    data, samplerate = sf.read("response.wav")
    return Audio(data, rate=samplerate)

def voice_assistant(user_input):
    response = ask_ai(user_input)
    print("AI:", response)
    return speak_openai(response)

speak_openai("Բարև, սա արդեն իրական AI ձայն է")

while True:
    user_input = input("Դու: ")

    if user_input.lower() in ["exit", "quit"]:
        break

    voice_assistant(user_input)

voice_assistant("Ինչ վարկեր ունեք")

!pip install SpeechRecognition
!apt-get install -y ffmpeg

import speech_recognition as sr
from IPython.display import Audio

from google.colab import output
from base64 import b64decode
import subprocess

def record_audio(seconds=5):
    print("Recording... Speak now!")

    js = f"""
    const sleep = time => new Promise(resolve => setTimeout(resolve, time));
    async function record() {{
      const stream = await navigator.mediaDevices.getUserMedia({{ audio: true }});
      const recorder = new MediaRecorder(stream);
      let chunks = [];

      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();

      await sleep({seconds * 1000});
      recorder.stop();

      return new Promise(resolve => {{
        recorder.onstop = () => {{
          const blob = new Blob(chunks);
          const reader = new FileReader();
          reader.readAsDataURL(blob);
          reader.onloadend = () => resolve(reader.result);
        }};
      }});
    }}
    record();
    """

    audio_data = output.eval_js(js)
    audio_bytes = b64decode(audio_data.split(',')[1])

    with open("input.webm", "wb") as f:
        f.write(audio_bytes)

    subprocess.run([
        "ffmpeg", "-y",
        "-i", "input.webm",
        "-ar", "16000",
        "-ac", "1",
        "input.wav"
    ])

    print("Recording + conversion done")

def speech_to_text():
    import speech_recognition as sr
    r = sr.Recognizer()

    with sr.AudioFile("input.wav") as source:
        audio = r.record(source)

    try:
        text = r.recognize_google(audio, language="hy-AM")
        print("You said:", text)
        return text
    except:
        print("Could not understand")
        return None

def full_voice_assistant():
    record_audio(5)

    user_text = speech_to_text()
    if not user_text:
        return

    response = ask_ai(user_text)
    print("AI:", response)

    return speak_openai(response)

full_voice_assistant()